[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs', 'mysql-client']

[phases.build]
cmds = [
  'composer install --no-interaction --prefer-dist',
  'npm install',
  'npm run build',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]
