[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs', 'mysql-client']

[phases.build]
cmds = [
    'composer install --no-dev',
    'npm install',
    'npm run build',
    'php artisan optimize'
]

[phases.deploy]
cmds = [
    'php artisan migrate --force',
    'php artisan serve --host 0.0.0.0 --port $PORT'
]
